import { Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import { prisma } from '../../lib/prisma';
import { AppError } from '../../lib/errors';
import { createBookingCheckout } from '../services/checkout.service';
import { refundPayment } from '../services/refund.service';
import { canAccessPayment } from '../../lib/resourceAuthorization';

const CheckoutSchema=z.object({bookingId:z.string().min(1),country:z.string().regex(/^[A-Z]{2}$/),purpose:z.enum(['STUDIO_BOOKING','BOOKING_DEPOSIT','SESSION_PAYMENT']).default('STUDIO_BOOKING'),paymentMethod:z.enum(['CARD','BANK_TRANSFER','MOBILE_MONEY','WALLET','LOCAL_PAYMENT_METHOD','CASH','OTHER']).default('CARD'),returnUrl:z.string().url()}).strict();
const jsonPayment=(p:any)=>({...p,amount_minor:p.amount_minor.toString(),platform_fee_minor:p.platform_fee_minor.toString(),merchant_net_minor:p.merchant_net_minor.toString()});
export async function checkout(req:Request,res:Response,next:NextFunction){try{const data=CheckoutSchema.parse(req.body);const key=req.header('Idempotency-Key');if(!key||key.length<8)throw new AppError('IDEMPOTENCY_KEY_REQUIRED',400);const result=await createBookingCheckout({...data,idempotencyKey:key,userId:(req as any).userId,userRole:(req as any).userRole,method:data.paymentMethod});res.status(result.idempotent?200:201).json({...result,payment:jsonPayment(result.payment)});}catch(e){next(e)}}
export async function listPayments(req:Request,res:Response,next:NextFunction){try{const uid=(req as any).userId,role=(req as any).userRole;let where:any={payer_id:uid};if(role==='STUDIO_ADMIN'){const staff=await prisma.studioStaff.findUnique({where:{user_id:uid}});if(!staff)throw new AppError('Forbidden',403);where={studio_id:staff.studio_id};}else if(role==='OIANO_ADMIN')where={};const rows=await prisma.oianoPayment.findMany({where,orderBy:{created_at:'desc'},take:100});res.json(rows.map(jsonPayment));}catch(e){next(e)}}
export async function getPayment(req:Request,res:Response,next:NextFunction){try{const p=await prisma.oianoPayment.findUnique({where:{id:req.params.id},include:{refunds:true,allocations:true,ledger_transactions:{include:{entries:{include:{account:true}}}},gateway_events:true}});if(!p)throw new AppError('PAYMENT_NOT_FOUND',404);const uid=(req as any).userId,role=(req as any).userRole;const staff=role==='STUDIO_ADMIN'?await prisma.studioStaff.findUnique({where:{user_id:uid}}):null;if(!canAccessPayment({payerId:p.payer_id,paymentStudioId:p.studio_id,actorId:uid,actorRole:role,actorStudioId:staff?.studio_id}))throw new AppError('PAYMENT_NOT_FOUND',404);res.json(JSON.parse(JSON.stringify(p,(_key,value)=>typeof value==='bigint'?value.toString():value)));}catch(e){next(e)}}
const RefundSchema=z.object({amountMinor:z.string().regex(/^\d+$/),reason:z.string().min(3).max(300)}).strict();
export async function refund(req:Request,res:Response,next:NextFunction){try{const data=RefundSchema.parse(req.body);const key=req.header('Idempotency-Key');if(!key||key.length<8)throw new AppError('IDEMPOTENCY_KEY_REQUIRED',400);const result=await refundPayment({paymentId:req.params.id,amountMinor:BigInt(data.amountMinor),reason:data.reason,idempotencyKey:key,actorId:(req as any).userId,actorRole:(req as any).userRole});res.status(result.idempotent?200:201).json({...result,refund:{...result.refund,amount_minor:result.refund.amount_minor.toString()}});}catch(e){next(e)}}
