import { useMutation } from '@tanstack/react-query';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Building2 } from 'lucide-react';
import { api } from '../lib/api';
import { useAuthStore } from '../store/auth.store';
export default function AcceptStudioInvitePage(){const[token]=useSearchParams();const navigate=useNavigate();const value=token.get('token')??'';
  // Staff routes check the account role; a membership alone gives an artist or producer account nothing (audit C04).
  const role=useAuthStore((state)=>state.user?.role);const creativeAccount=role==='ARTIST'||role==='PRODUCER';
const accept=useMutation({mutationFn:()=>api.post('/studio/team/invitations/accept',{token:value}),onSuccess:()=>navigate('/dashboard',{replace:true})});return <main className="grid min-h-screen place-items-center bg-studio-bg p-5 text-white"><section className="w-full max-w-md rounded-3xl border border-white/[.08] bg-studio-surface p-8 text-center"><Building2 size={24} className="mx-auto text-dome"/><p className="mt-6 text-[9px] font-mono uppercase tracking-[.25em] text-zinc-600">Studio invitation</p><h1 className="mt-3 font-display text-3xl">Join the team</h1><p className="mt-4 text-xs leading-5 text-zinc-500">{creativeAccount?'Accepting adds you to this studio’s team. For now, studio tools work only on a studio account, so this artist or creative professional account will not get studio access.':'Accepting adds this studio account to the team, with the position and permissions the studio chose.'}</p>{accept.isError&&<p role="alert" className="mt-5 rounded-xl border border-red-500/20 p-3 text-xs text-red-300">{(accept.error as any)?.response?.data?.error??'This invitation is invalid or expired.'}</p>}<button disabled={!value||accept.isPending} onClick={()=>accept.mutate()} className="mt-7 w-full rounded-xl bg-dome px-4 py-3 text-xs font-semibold text-black disabled:opacity-40">{accept.isPending?'Accepting…':'Accept studio invitation'}</button></section></main>}
