import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { AlertCircle, Bell, FolderKanban, MessageSquareText, Search, ShieldCheck, Users } from 'lucide-react';
import { api } from '../lib/api';
import { useAuthStore } from '../store/auth.store';

type Notice={id:string;type:string;title:string;body:string;payload:Record<string,unknown>;read_at:string|null;created_at:string};
type Booking={id:string;status:string;starts_at:string;service?:{name?:string}|null;room?:{name?:string}|null;studio?:{name?:string}|null;artist?:{name?:string;alias?:string|null}|null;project?:{id:string;title:string}|null};
type Project={id:string;title:string;phase:string;updated_at?:string;artist?:{name?:string;alias?:string|null}|null;producer?:{name?:string;alias?:string|null}|null;bookings?:Booking[]};
type Connection={id:string;status:string;initiator:{id:string;user_id:string;name:string;alias?:string|null};recipient:{id:string;user_id:string;name:string;alias?:string|null};messages:Array<{body:string;created_at:string}>};
type View='priority'|'conversations'|'sessions'|'projects'|'system';

const views:[View,string,typeof Bell][]=[['priority','Priority',AlertCircle],['conversations','Conversations',Users],['sessions','Sessions',MessageSquareText],['projects','Projects',FolderKanban],['system','System',ShieldCheck]];
const relative=(value:string)=>{const mins=Math.floor((Date.now()-new Date(value).getTime())/60000);return mins<1?'Now':mins<60?`${mins}m`:mins<1440?`${Math.floor(mins/60)}h`:new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short'})};
const noticeHref=(n:Notice)=>{const p=n.payload as any;return typeof p.action_url==='string'&&p.action_url.startsWith('/')?p.action_url:p.booking_id?`/bookings/${p.booking_id}`:null};
const ACTION_TYPES=['CONTRIBUTION_INVITATION','PROMOTIONAL_CONSENT_REQUESTED','RIGHTS_PROPOSAL','RIGHTS_PROPOSED','PROJECT_CREDITS_PROPOSED','SESSION_DELIVERED','CREDIT_REQUEST'];
const actionKind=(type:string)=>{const t=type.toUpperCase();return t.includes('RIGHTS')?'Rights':t.includes('CREDIT')?'Credits':t.includes('CONSENT')?'Consent':t.includes('CONTRIBUTION')?'Invitation':t.includes('DELIVERED')?'Delivery':'Decision'};
const actionLabel=(type:string)=>{const t=type.toUpperCase();return t.includes('RIGHTS')?'Review shares':t.includes('CREDIT')?'Review credit':t.includes('CONSENT')?'Review consent':t.includes('CONTRIBUTION')?'Review invitation':t.includes('DELIVERED')?'Review delivery':'Review action'};
const isAction=(notice:Notice)=>ACTION_TYPES.includes(notice.type.toUpperCase())||(notice.payload as any)?.priority==='CRITICAL';

export default function CommunicationsPage(){
  const user=useAuthStore(s=>s.user);const[params,setParams]=useSearchParams();const requested=params.get('view') as View|null;const[query,setQuery]=useState('');const view:View=views.some(([id])=>id===requested)?requested!:'priority';
  const isArtist=user?.role==='ARTIST',isProducer=user?.role==='PRODUCER';
  const notices=useQuery<Notice[]>({queryKey:['communications','notices'],queryFn:async()=>(await api.get('/notifications')).data});
  const connections=useQuery<Connection[]>({queryKey:['communications','connections'],queryFn:async()=>(await api.get('/connect')).data,enabled:isArtist});
  const bookings=useQuery<Booking[]>({queryKey:['communications','bookings'],queryFn:async()=>{const r=await api.get('/bookings',{params:{limit:100}});return Array.isArray(r.data)?r.data:r.data?.data??[]},enabled:!isProducer});
  const projects=useQuery<Project[]>({queryKey:['communications','projects',user?.role],queryFn:async()=>(await api.get(isProducer?'/producer/projects':'/artist-projects')).data,enabled:isArtist||isProducer});
  const allNotices=notices.data??[],allConnections=connections.data??[],allBookings=bookings.data??[],allProjects=projects.data??[];
  const actionable=allNotices.filter(isAction);
  const counts:Record<View,number>={priority:actionable.length,conversations:allConnections.length,sessions:allBookings.length,projects:allProjects.length,system:allNotices.filter(n=>!actionable.includes(n)).length};
  const normalized=query.trim().toLowerCase();const match=(...text:(string|undefined|null)[])=>!normalized||text.join(' ').toLowerCase().includes(normalized);
  const other=(c:Connection)=>c.initiator.user_id===user?.id?c.recipient:c.initiator;
  const loading=notices.isLoading||connections.isLoading||bookings.isLoading||projects.isLoading;
  const empty=<div className="rounded-2xl border border-dashed border-white/[.08] p-12 text-center"><Bell className="mx-auto text-zinc-800"/><p className="mt-4 text-sm text-zinc-500">Nothing in this view</p><p className="mt-1 text-xs text-zinc-700">New work and decisions will appear with their professional context.</p></div>;
  return <main className="min-h-screen bg-studio-bg pb-28 text-zinc-100">
    <header className="border-b border-white/[.06] px-5 py-8 md:px-8"><div className="mx-auto max-w-[1380px]"><p className="text-[9px] font-mono uppercase tracking-[.25em] text-dome">OIANO Communications</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-display text-4xl">Every conversation connected to the work.</h1><p className="mt-2 text-sm text-zinc-600">Messages, sessions, projects and formal decisions under one professional identity.</p></div><label className="flex w-full max-w-sm items-center gap-2 rounded-xl border border-white/[.07] bg-white/[.02] px-3"><Search size={14} className="text-zinc-700"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search work and people" className="w-full bg-transparent py-3 text-xs outline-none placeholder:text-zinc-700"/></label></div></div></header>
    <div className="mx-auto grid max-w-[1380px] gap-6 px-5 py-6 md:px-8 lg:grid-cols-[220px_minmax(0,1fr)]">
      <nav aria-label="Communication categories" className="flex gap-2 overflow-x-auto lg:flex-col">{views.map(([id,label,Icon])=><button key={id} onClick={()=>setParams({view:id})} className={`flex min-w-[150px] items-center gap-3 rounded-xl px-3 py-3 text-left text-xs lg:min-w-0 ${view===id?'bg-dome/[.1] text-dome':'text-zinc-600 hover:bg-white/[.025] hover:text-zinc-300'}`}><Icon size={14}/>{label}<span className="ml-auto rounded-full bg-black/30 px-2 py-0.5 text-[9px]">{counts[id]}</span></button>)}</nav>
      <section>{loading?<div className="grid min-h-72 place-items-center text-[9px] font-mono tracking-widest text-zinc-700">OPENING COMMUNICATIONS…</div>:<div className="space-y-2">
        {view==='priority'&&(actionable.filter(n=>match(n.title,n.body,actionKind(n.type))).map(n=>{const href=noticeHref(n);const urgent=(n.payload as any)?.priority==='CRITICAL';const card=<article className={`rounded-2xl border p-5 ${urgent?'border-red-400/15 bg-red-400/[.035]':'border-amber-400/10 bg-amber-400/[.025]'}`}><div className="flex items-start gap-4"><AlertCircle size={17} className={`mt-0.5 shrink-0 ${urgent?'text-red-300':'text-amber-300'}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2 py-1 text-[7px] font-mono uppercase tracking-wider ${urgent?'border-red-300/20 text-red-300':'border-amber-300/20 text-amber-300'}`}>Action required</span><span className="rounded-full border border-white/[.06] px-2 py-1 text-[7px] font-mono uppercase text-zinc-600">{actionKind(n.type)}</span><time className="ml-auto text-[9px] text-zinc-700">{relative(n.created_at)}</time></div><h2 className="mt-3 text-sm font-semibold">{n.title}</h2><p className="mt-2 text-xs leading-5 text-zinc-600">{n.body}</p><div className="mt-4 flex items-center justify-between border-t border-white/[.05] pt-3"><span className="text-[9px] text-zinc-700">Decision is recorded in its original work context</span>{href?<span className={`rounded-lg px-3 py-2 text-[9px] font-semibold ${urgent?'bg-red-300 text-black':'bg-amber-300 text-black'}`}>{actionLabel(n.type)} →</span>:<span className="text-[9px] text-zinc-700">Context unavailable</span>}</div></div></div></article>;return href?<Link key={n.id} to={href}>{card}</Link>:<div key={n.id}>{card}</div>}) )}
        {view==='conversations'&&allConnections.filter(c=>{const p=other(c);return match(p.name,p.alias,c.messages[0]?.body)}).map(c=>{const p=other(c);return <Link key={c.id} to={`/connect/${p.id}`} className="card-lift flex items-center gap-4 rounded-2xl border border-white/[.06] p-5 hover:border-dome/20"><span className="grid h-10 w-10 place-items-center rounded-full bg-violet-400/10 text-violet-300"><Users size={16}/></span><span className="min-w-0 flex-1"><b className="text-sm">{p.alias||p.name}</b><span className="mt-1 block truncate text-xs text-zinc-600">{c.messages[0]?.body||`${c.status.toLowerCase()} professional connection`}</span></span><span className="text-[9px] text-zinc-700">Open →</span></Link>})}
        {view==='sessions'&&allBookings.filter(b=>match(b.service?.name,b.room?.name,b.artist?.name,b.studio?.name,b.status)).map(b=><Link key={b.id} to={`/bookings/${b.id}`} className="card-lift flex items-center gap-4 rounded-2xl border border-white/[.06] p-5 hover:border-dome/20"><MessageSquareText size={17} className="text-dome"/><span className="min-w-0 flex-1"><b className="text-sm">{b.service?.name||'Studio session'}</b><span className="mt-1 block text-xs text-zinc-600">{b.artist?.alias||b.artist?.name||b.studio?.name||'Studio team'} · {b.room?.name||'Room'} · {b.status.replaceAll('_',' ')}</span></span><time className="text-[9px] text-zinc-700">{new Date(b.starts_at).toLocaleDateString()}</time></Link>)}
        {view==='projects'&&allProjects.filter(p=>match(p.title,p.phase,p.artist?.name,p.producer?.name)).map(p=><Link key={p.id} to={isProducer?`/producer/projects/${p.id}`:`/projects?project=${p.id}`} className="card-lift flex items-center gap-4 rounded-2xl border border-white/[.06] p-5 hover:border-dome/20"><FolderKanban size={17} className="text-dome"/><span className="min-w-0 flex-1"><b className="text-sm">{p.title}</b><span className="mt-1 block text-xs text-zinc-600">{p.phase.replaceAll('_',' ')} · {p.bookings?.length??0} sessions</span></span><span className="text-[9px] text-zinc-700">Workroom →</span></Link>)}
        {view==='system'&&allNotices.filter(n=>!actionable.includes(n)&&match(n.title,n.body)).map(n=><article key={n.id} className="flex gap-4 rounded-2xl border border-white/[.05] p-5"><ShieldCheck size={16} className="text-zinc-600"/><div className="flex-1"><b className="text-sm text-zinc-400">{n.title}</b><p className="mt-1 text-xs text-zinc-700">{n.body}</p></div><time className="text-[9px] text-zinc-800">{relative(n.created_at)}</time></article>)}
        {counts[view]===0&&empty}
      </div>}</section>
    </div>
  </main>;
}
