import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarDays, Check, FileCheck2, FolderKanban, Scale, UsersRound, X } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import MessageThread from '../components/MessageThread';
import { useToast } from '../components/Toast';
import { api } from '../lib/api';
import { useAuthStore } from '../store/auth.store';

const label = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, c => c.toUpperCase());
const date = (value: string) => new Date(value).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' });

type Workspace = {
  id: string; role: string; display_name: string;
  project: {
    id: string; title: string; phase: string; notes?: string | null;
    producer: { name: string; alias?: string | null }; artist?: { name: string; alias?: string | null } | null;
    participants: Array<{ id: string; display_name: string; role: string }>;
    credits: Array<{ id: string; credited_name: string; role: string; scope?: string | null; status: string; participant_id?: string | null }>;
    rights_agreements: Array<{ id: string; title: string; agreement_type: string; status: string; shares: Array<{ id: string; holder_name: string; role: string; percentage: string | number }>; decisions: Array<{ id: string; holder_user_id: string; holder_name: string; status: string; note?: string | null }> }>;
    bookings: Array<{ id: string; status: string; starts_at: string; studio: { name: string }; room?: { name: string } | null; service?: { name: string } | null; deliverables: Array<{ id: string; title: string; status: string; current_version: number; versions: Array<{ id: string; version_number: number; created_at: string }>; reviews: Array<{ id: string; decision: string; note?: string | null; created_at: string }> }> }>;
  };
};

export default function ContributionWorkspacePage() {
  const { participantId = '' } = useParams();
  const qc = useQueryClient();
  const toast = useToast();
  const user = useAuthStore(state => state.user);
  const { data, isLoading, isError } = useQuery<Workspace>({ queryKey: ['contribution-workspace', participantId], queryFn: async () => (await api.get(`/contributions/${participantId}/workspace`)).data, enabled: !!participantId });
  const creditDecision = useMutation({
    mutationFn: ({ id, decision }: { id: string; decision: 'CONFIRM' | 'DISPUTE' }) => api.patch(`/contributions/credits/${id}/respond`, { decision }),
    onSuccess: (_, variables) => { qc.invalidateQueries({ queryKey: ['contribution-workspace', participantId] }); qc.invalidateQueries({ queryKey: ['network-metrics'] }); toast.success(variables.decision === 'CONFIRM' ? 'Credit confirmed' : 'Credit disputed'); },
    onError: (error: any) => toast.error(error?.response?.data?.error ?? 'Credit decision failed'),
  });
  const rightsDecision = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'APPROVE' | 'DISPUTE' }) => api.patch(`/contributions/rights/${id}/respond`, { action, note: action === 'DISPUTE' ? 'The proposed share needs correction.' : undefined }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['contribution-workspace', participantId] }); toast.success('Rights decision recorded'); }, onError: (error: any) => toast.error(error?.response?.data?.error ?? 'Rights decision failed') });
  if (isLoading) return <main className="grid min-h-screen place-items-center bg-[#070809] text-xs text-zinc-600">OPENING CONTRIBUTION WORKSPACE…</main>;
  if (isError || !data) return <main className="grid min-h-screen place-items-center bg-[#070809] px-6 text-center text-zinc-400"><div><h1 className="text-2xl text-white">Workspace unavailable</h1><p className="mt-2 text-sm text-zinc-600">Only accepted contributors can open this project workspace.</p><Link to="/contributions" className="mt-5 inline-block text-violet-300">Return to inbox</Link></div></main>;
  const project = data.project;
  const myCredits = project.credits.filter(credit => credit.participant_id === data.id);
  const deliverables = project.bookings.flatMap(booking => booking.deliverables.map(item => ({ ...item, booking })));
  return <main className="min-h-screen bg-[#070809] px-5 py-8 text-zinc-100 md:px-8"><div className="mx-auto max-w-7xl">
    <header className="rounded-3xl border border-violet-300/15 bg-[radial-gradient(circle_at_15%_0%,rgba(155,138,251,.13),transparent_38%),#0c0e10] p-6 md:p-8"><Link to="/contributions" className="text-[9px] font-mono uppercase tracking-wider text-zinc-600">← Contribution inbox</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-5"><div><p className="text-[9px] font-mono uppercase tracking-[.22em] text-violet-300">{label(data.role)} · Accepted contributor</p><h1 className="mt-2 text-4xl font-semibold">{project.title}</h1><p className="mt-3 text-sm text-zinc-500">Led by {project.producer.alias || project.producer.name}{project.artist ? ` · with ${project.artist.alias || project.artist.name}` : ''}</p></div><span className="rounded-full border border-violet-300/20 px-4 py-2 text-[9px] font-mono uppercase text-violet-300">{label(project.phase)}</span></div></header>

    <section className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-white/[.06] bg-[#0c0e10] p-5"><UsersRound size={16} className="text-violet-300"/><p className="mt-4 text-2xl">{project.participants.length + (project.artist ? 2 : 1)}</p><p className="mt-1 text-[9px] uppercase text-zinc-700">Project people</p></div><div className="rounded-2xl border border-white/[.06] bg-[#0c0e10] p-5"><CalendarDays size={16} className="text-[#5A9BCB]"/><p className="mt-4 text-2xl">{project.bookings.length}</p><p className="mt-1 text-[9px] uppercase text-zinc-700">Linked sessions</p></div><div className="rounded-2xl border border-white/[.06] bg-[#0c0e10] p-5"><FileCheck2 size={16} className="text-emerald-400"/><p className="mt-4 text-2xl">{deliverables.length}</p><p className="mt-1 text-[9px] uppercase text-zinc-700">Deliverables tracked</p></div></section>

    <div className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-6">
      <section><div className="mb-3 flex items-center gap-2"><FolderKanban size={15} className="text-[#5A9BCB]"/><h2 className="text-xs font-semibold uppercase tracking-wider">Sessions and deliverables</h2></div><div className="space-y-3">{project.bookings.map(booking=><article key={booking.id} className="rounded-2xl border border-white/[.06] bg-[#0c0e10] p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-medium">{booking.studio.name} · {booking.room?.name ?? 'Studio room'}</p><p className="mt-1 text-[9px] text-zinc-600">{booking.service?.name ?? 'Creative session'} · {date(booking.starts_at)}</p></div><span className="text-[8px] font-mono uppercase text-[#5A9BCB]">{label(booking.status)}</span></div>{booking.deliverables.map(item=><div key={item.id} className="mt-3 rounded-xl border border-white/[.05] bg-black/20 p-4"><div className="flex justify-between gap-3"><div><p className="text-xs text-zinc-300">{item.title}</p><p className="mt-1 text-[8px] text-zinc-700">Version {item.current_version} · {item.versions.length} recorded version{item.versions.length===1?'':'s'}</p></div><span className="text-[8px] uppercase text-zinc-500">{label(item.status)}</span></div>{item.reviews[0]?.note&&<p className="mt-3 border-l border-amber-300/30 pl-3 text-[10px] leading-5 text-zinc-500">Latest review: {item.reviews[0].note}</p>}</div>)}</article>)}{!project.bookings.length&&<div className="rounded-2xl border border-dashed border-white/[.07] p-8 text-center text-xs text-zinc-700">No studio sessions linked yet.</div>}</div></section>
      <MessageThread variant="project" endpoint={`/projects/${project.id}/messages`} queryKey={['project-messages', project.id]} sseMatch={event=>event?.type==='new_project_message'&&event?.projectId===project.id} title="Project conversation" subtitle="Shared with accepted project members" emptyTitle="Start the project conversation" emptySubtitle="Decisions stay attached to this work." placeholder="Message the project team…" />
    </div><aside className="space-y-6">
      <section className="rounded-2xl border border-white/[.06] bg-[#0c0e10] p-5"><h2 className="text-xs font-semibold uppercase tracking-wider">Your verified credits</h2><div className="mt-4 space-y-3">{myCredits.map(credit=><div key={credit.id} className="rounded-xl border border-white/[.05] p-4"><p className="text-xs">{label(credit.role)}</p><p className="mt-1 text-[9px] text-zinc-600">{credit.scope || 'Whole project'}</p>{credit.status==='DRAFT'?<div className="mt-3 flex gap-2"><button disabled={creditDecision.isPending} onClick={()=>creditDecision.mutate({id:credit.id,decision:'CONFIRM'})} className="flex items-center gap-1 rounded-lg bg-emerald-400 px-3 py-2 text-[8px] font-semibold text-black"><Check size={11}/> Confirm</button><button disabled={creditDecision.isPending} onClick={()=>creditDecision.mutate({id:credit.id,decision:'DISPUTE'})} className="flex items-center gap-1 rounded-lg border border-red-400/15 px-3 py-2 text-[8px] text-red-300"><X size={11}/> Dispute</button></div>:<p className="mt-3 text-[8px] font-mono uppercase text-zinc-500">{credit.status}</p>}</div>)}{!myCredits.length&&<p className="text-xs leading-5 text-zinc-700">No credit has been assigned to your contribution yet.</p>}</div></section>
      <section className="rounded-2xl border border-white/[.06] bg-[#0c0e10] p-5"><div className="flex items-center gap-2"><Scale size={15} className="text-amber-300"/><h2 className="text-xs font-semibold uppercase tracking-wider">Rights record</h2></div><p className="mt-2 text-[9px] leading-4 text-zinc-700">Credits document contribution. Ownership remains a separate agreement.</p><div className="mt-4 space-y-3">{project.rights_agreements.map(agreement=>{const mine=agreement.decisions.find(decision=>decision.holder_user_id===user?.id);return <div key={agreement.id} className="rounded-xl border border-white/[.05] p-4"><div className="flex justify-between gap-3"><p className="text-xs">{agreement.title}</p><span className="text-[8px] uppercase text-amber-300/70">{agreement.status}</span></div><div className="mt-3 space-y-1">{agreement.shares.map(share=><p key={share.id} className="flex justify-between text-[9px] text-zinc-600"><span>{share.holder_name} · {share.role}</span><span>{Number(share.percentage)}%</span></p>)}</div>{mine&&<div className="mt-3 border-t border-white/[.05] pt-3"><p className="text-[8px] uppercase text-zinc-600">Your decision · {mine.status}</p>{mine.status==='PENDING'&&<div className="mt-2 flex gap-2"><button disabled={rightsDecision.isPending} onClick={()=>rightsDecision.mutate({id:agreement.id,action:'APPROVE'})} className="rounded-lg bg-amber-300 px-3 py-2 text-[8px] font-semibold text-black">Approve my share</button><button disabled={rightsDecision.isPending} onClick={()=>rightsDecision.mutate({id:agreement.id,action:'DISPUTE'})} className="rounded-lg border border-red-400/15 px-3 py-2 text-[8px] text-red-300">Request correction</button></div>}</div>}</div>})}{!project.rights_agreements.length&&<p className="text-xs text-zinc-700">No ownership proposal recorded.</p>}</div></section>
    </aside></div>
  </div></main>;
}
