import { FileClock, Filter, ShieldCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../lib/api';
import MaintenanceShell from '../components/MaintenanceShell';

type Log={id:string;actor_email:string;actor_role:string;action:string;method:string|null;path:string|null;ip_hash:string|null;metadata:Record<string,unknown>;created_at:string};

export default function MaintenanceAuditPage(){
 const[action,setAction]=useState('ALL');
 const{data=[],isLoading,error}=useQuery<Log[]>({queryKey:['maintenance-audit'],queryFn:async()=>(await api.get('/maintenance/audit?limit=200')).data,refetchInterval:30_000});
 const actions=useMemo(()=>['ALL',...Array.from(new Set(data.map(log=>log.action)))],[data]);const logs=action==='ALL'?data:data.filter(log=>log.action===action);
 return <MaintenanceShell>
 <section className="mx-auto max-w-7xl px-5 py-10 md:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-[9px] font-mono uppercase tracking-[.28em] text-[#C9A84C]">Security · Audit</p><h1 className="font-display text-4xl">Every privileged view, recorded.</h1><p className="mt-3 text-sm text-zinc-600">Append-only evidence for OIANO administrative access.</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-500/15 bg-emerald-500/[.04] px-3 py-1.5 text-[9px] font-mono text-emerald-500"><ShieldCheck size={11}/> IMMUTABLE</div></div>
 <div className="mt-9 grid gap-3 sm:grid-cols-3"><article className="metric-enter rounded-2xl border border-white/[.065] bg-studio-surface p-5"><FileClock size={16} className="text-dome"/><p className="mt-6 text-2xl font-semibold">{data.length}</p><p className="mt-2 text-[9px] font-mono uppercase text-zinc-600">Recent events</p></article><article className="rounded-2xl border border-white/[.065] bg-studio-surface p-5"><ShieldCheck size={16} className="text-emerald-500"/><p className="mt-6 text-sm font-semibold">Update/delete blocked</p><p className="mt-2 text-[9px] font-mono uppercase text-zinc-600">Database enforced</p></article><article className="rounded-2xl border border-white/[.065] bg-studio-surface p-5"><Filter size={16} className="text-[#C9A84C]"/><select value={action} onChange={e=>setAction(e.target.value)} className="mt-5 w-full rounded-lg border border-white/[.07] bg-[#08090b] p-2 text-xs text-zinc-400 outline-none">{actions.map(value=><option key={value}>{value}</option>)}</select></article></div>
 {isLoading?<p className="mt-12 text-xs text-zinc-700">Reading audit evidence…</p>:error?<div role="alert" className="mt-8 rounded-xl border border-red-500/20 p-5 text-red-300">Audit evidence is unavailable.</div>:<article className="mt-3 overflow-x-auto rounded-2xl border border-white/[.065] bg-studio-surface p-5"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b border-white/[.06] text-[8px] font-mono uppercase tracking-wider text-zinc-700"><th className="pb-3">Time</th><th>Actor</th><th>Action</th><th>Request</th><th>Network fingerprint</th><th>Result</th></tr></thead><tbody>{logs.map(log=><tr key={log.id} className="border-b border-white/[.04] text-xs"><td className="py-4 text-zinc-600">{new Date(log.created_at).toLocaleString()}</td><td>{log.actor_email}<p className="mt-1 text-[8px] text-zinc-700">{log.actor_role}</p></td><td><span className="rounded-full border border-dome/15 bg-dome/[.04] px-2 py-1 text-[8px] font-mono text-dome">{log.action}</span></td><td className="text-zinc-500">{log.method} {log.path}</td><td className="font-mono text-[9px] text-zinc-700">{log.ip_hash??'—'}</td><td className="text-emerald-500">{String(log.metadata?.status_code??'SUCCESS')}</td></tr>)}</tbody></table>{!logs.length&&<p className="py-10 text-center text-xs text-zinc-700">No audit events match this filter.</p>}</article>}</section>
 </MaintenanceShell>;
}
