import { AlertTriangle, CalendarCheck, CircleDollarSign, Clock3, TrendingUp } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../lib/api';
import MaintenanceShell from '../components/MaintenanceShell';
import SearchInput from '../components/SearchInput';
import { STATUS_HEX } from '../lib/bookingStatus';

type Booking={id:string;created_at:string;starts_at:string;ends_at:string;status:string;total_usd:number;studio:{id:string;name:string};artist:{id:string;name:string;alias:string|null};room:string;service:string;engineer:string|null;payment:{status:string;amount_usd:number;provider:string}|null};
type Response={totals:{bookings:number;paid:number;paid_volume:number;payment_exceptions:number;actionable:number};states:Record<string,number>;completion_rate:number;cancellation_rate:number;bookings:Booking[]};
const statuses=['ALL','PENDING','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW'];
const statusTone = STATUS_HEX as Record<string, string>;

export default function MaintenanceBookingsPage(){
 const [status,setStatus]=useState('ALL');const [query,setQuery]=useState('');
 const {data,isLoading,error}=useQuery<Response>({queryKey:['maintenance-bookings'],queryFn:async()=>(await api.get('/maintenance/bookings')).data,refetchInterval:30_000});
 const bookings=useMemo(()=>data?.bookings.filter(b=>(status==='ALL'||b.status===status)&&`${b.artist.alias??b.artist.name} ${b.studio.name} ${b.room} ${b.service} ${b.id}`.toLowerCase().includes(query.toLowerCase()))??[],[data,status,query]);
 return <MaintenanceShell>
 <section className="mx-auto max-w-[1380px] px-5 py-10 md:px-8"><p className="mb-3 text-[9px] font-mono uppercase tracking-[.28em] text-dome">Network · Bookings</p><h1 className="font-display text-4xl">Demand into delivery.</h1><p className="mt-3 text-sm text-zinc-600">Conversion, exceptions and session flow across every studio.</p>
 {isLoading?<p className="mt-12 text-xs text-zinc-700">Reading booking flow…</p>:error||!data?<div role="alert" className="mt-10 rounded-xl border border-red-500/20 p-5 text-red-300">Booking intelligence is unavailable.</div>:<><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[CalendarCheck,'Bookings',data.totals.bookings],[TrendingUp,'Completion',`${data.completion_rate}%`],[CircleDollarSign,'Paid volume',`$${data.totals.paid_volume.toLocaleString()}`],[AlertTriangle,'Needs action',data.totals.actionable],[Clock3,'Cancellation',`${data.cancellation_rate}%`]].map(([Icon,label,value]:any)=><article key={label} className="metric-enter rounded-2xl border border-white/[.065] bg-studio-surface p-5"><Icon size={15} className={label==='Needs action'&&Number(value)>0?'text-amber-400':'text-dome'}/><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-mono uppercase tracking-wider text-zinc-600">{label}</p></article>)}</div>
 <article className="mt-3 rounded-2xl border border-white/[.065] bg-studio-surface p-5"><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{statuses.slice(1).map(s=><button onClick={()=>setStatus(s)} key={s} className={`rounded-xl border p-3 text-left ${status===s?'border-white/[.14] bg-white/[.04]':'border-white/[.05]'}`}><span className="text-lg font-semibold">{data.states[s]??0}</span><span className="mt-1 block text-[8px] font-mono" style={{color:statusTone[s]}}>{s.replace('_',' ')}</span></button>)}</div><div className="mt-5 flex flex-wrap gap-3"><SearchInput value={query} onChange={setQuery} placeholder="Search artist, studio, room or booking ID" className="min-w-[260px] flex-1" /> {status!=='ALL'&&<button onClick={()=>setStatus('ALL')} className="rounded-xl border border-white/[.06] px-4 text-[9px] font-mono text-zinc-600">CLEAR FILTER</button>}</div>
 <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1020px] text-left"><thead><tr className="border-b border-white/[.06] text-[8px] font-mono uppercase tracking-wider text-zinc-700"><th className="pb-3">Session</th><th>Studio</th><th>Schedule</th><th>Value</th><th>Booking state</th><th>Payment</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id} className="border-b border-white/[.04] text-xs"><td className="py-4"><b className="font-medium">{b.artist.alias||b.artist.name}</b><p className="mt-1 text-[9px] text-zinc-700">{b.service} · {b.room}</p></td><td className="text-zinc-500">{b.studio.name}<p className="mt-1 text-[9px] text-zinc-700">{b.engineer||'Unassigned'}</p></td><td className="text-zinc-500">{new Date(b.starts_at).toLocaleDateString()}<p className="mt-1 text-[9px] text-zinc-700">{new Date(b.starts_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p></td><td>${b.total_usd.toLocaleString()}</td><td><span className="rounded-full border px-2 py-1 text-[8px] font-mono" style={{color:statusTone[b.status],borderColor:`${statusTone[b.status]}33`}}>{b.status.replace('_',' ')}</span></td><td><span className={`text-[9px] font-mono ${b.payment?.status==='FAILED'?'text-red-400':b.payment?.status==='PAID'?'text-emerald-400':'text-zinc-600'}`}>{b.payment?.status??'UNPAID'}</span><p className="mt-1 text-[8px] text-zinc-800">{b.payment?.provider??'—'}</p></td></tr>)}</tbody></table>{!bookings.length&&<p className="py-10 text-center text-xs text-zinc-700">No bookings match this view.</p>}</div></article></>}
 </section></MaintenanceShell>;
}
