import { AlertTriangle, ArrowLeft, Building2, CalendarCheck, CircleDollarSign, Clock3, LogOut, Search, Settings, TrendingUp, Users, Wrench } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import OianoBrand from '../components/OianoBrand';
import { useAuthStore } from '../store/auth.store';
import { api } from '../lib/api';
const SunMark = ({size}:{size:number}) => <OianoBrand variant="icon" size={size}/>;

type Booking={id:string;created_at:string;starts_at:string;ends_at:string;status:string;total_usd:number;studio:{id:string;name:string};artist:{id:string;name:string;alias:string|null};room:string;service:string;engineer:string|null;payment:{status:string;amount_usd:number;provider:string}|null};
type Response={totals:{bookings:number;paid:number;paid_volume:number;payment_exceptions:number;actionable:number};states:Record<string,number>;completion_rate:number;cancellation_rate:number;bookings:Booking[]};
const statuses=['ALL','PENDING','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW'];
const items=[{label:'Overview',icon:ArrowLeft,to:'/maintenance'},{label:'Studios',icon:Building2,to:'/maintenance/studios'},{label:'Creators',icon:Users,to:'/maintenance/creators'},{label:'Bookings',icon:CalendarCheck,active:true},{label:'Finance',icon:CircleDollarSign,to:'/maintenance/finance'},{label:'System health',icon:Wrench,to:'/maintenance/health'}];
const statusTone:Record<string,string>={PENDING:'#f59e0b',CONFIRMED:'#5A9BCB',IN_PROGRESS:'#34d399',COMPLETED:'#a1a1aa',CANCELLED:'#ef4444',NO_SHOW:'#f97316'};

export default function MaintenanceBookingsPage(){
 const navigate=useNavigate();const {user,logout}=useAuthStore();const [status,setStatus]=useState('ALL');const [query,setQuery]=useState('');
 const {data,isLoading,error}=useQuery<Response>({queryKey:['maintenance-bookings'],queryFn:async()=>(await api.get('/maintenance/bookings')).data,refetchInterval:30_000});
 const bookings=useMemo(()=>data?.bookings.filter(b=>(status==='ALL'||b.status===status)&&`${b.artist.alias??b.artist.name} ${b.studio.name} ${b.room} ${b.service} ${b.id}`.toLowerCase().includes(query.toLowerCase()))??[],[data,status,query]);
 return <main className="min-h-screen bg-[#060708] text-white md:pl-[238px]"><aside className="fixed inset-y-0 left-0 z-30 hidden w-[238px] flex-col border-r border-white/[.065] bg-[#08090b] md:flex"><div className="flex h-[76px] items-center gap-3 border-b border-white/[.06] px-6"><SunMark size={26}/><div><p className="text-sm font-semibold tracking-[.12em]">OIANO</p><p className="text-[8px] font-mono uppercase tracking-[.22em] text-zinc-600">Maintenance</p></div></div><nav className="flex-1 space-y-1 p-4">{items.map(({label,icon:Icon,to,active})=><button key={label} disabled={!to&&!active} onClick={()=>to&&navigate(to)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-xs ${active?'bg-dome/[.1] text-dome':'text-zinc-600 hover:bg-white/[.025] hover:text-zinc-400 disabled:cursor-default'}`}><Icon size={15}/>{label}{active&&<i className="ml-auto h-1.5 w-1.5 rounded-full bg-dome"/>}</button>)}</nav><p className="truncate border-t border-white/[.06] p-7 text-[9px] text-zinc-800">{user?.email}</p></aside>
 <header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-white/[.065] bg-[#060708]/90 px-5 backdrop-blur-xl md:px-8"><button onClick={()=>navigate('/maintenance')} className="flex items-center gap-2 text-xs text-zinc-600 hover:text-white"><ArrowLeft size={14}/> Network overview</button><div className="flex gap-2"><button className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.06] text-zinc-600"><Settings size={15}/></button><button onClick={()=>{logout();navigate('/enter')}} className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.06] text-zinc-600"><LogOut size={15}/></button></div></header>
 <section className="mx-auto max-w-[1380px] px-5 py-10 md:px-8"><p className="mb-3 text-[9px] font-mono uppercase tracking-[.28em] text-dome">Network · Bookings</p><h1 className="font-display text-4xl">Demand into delivery.</h1><p className="mt-3 text-sm text-zinc-600">Conversion, exceptions and session flow across every studio.</p>
 {isLoading?<p className="mt-12 text-xs text-zinc-700">Reading booking flow…</p>:error||!data?<div role="alert" className="mt-10 rounded-xl border border-red-500/20 p-5 text-red-300">Booking intelligence is unavailable.</div>:<><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[CalendarCheck,'Bookings',data.totals.bookings],[TrendingUp,'Completion',`${data.completion_rate}%`],[CircleDollarSign,'Paid volume',`$${data.totals.paid_volume.toLocaleString()}`],[AlertTriangle,'Needs action',data.totals.actionable],[Clock3,'Cancellation',`${data.cancellation_rate}%`]].map(([Icon,label,value]:any)=><article key={label} className="rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-5"><Icon size={15} className={label==='Needs action'&&Number(value)>0?'text-amber-400':'text-dome'}/><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-mono uppercase tracking-wider text-zinc-600">{label}</p></article>)}</div>
 <article className="mt-3 rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-5"><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{statuses.slice(1).map(s=><button onClick={()=>setStatus(s)} key={s} className={`rounded-xl border p-3 text-left ${status===s?'border-white/[.14] bg-white/[.04]':'border-white/[.05]'}`}><span className="text-lg font-semibold">{data.states[s]??0}</span><span className="mt-1 block text-[8px] font-mono" style={{color:statusTone[s]}}>{s.replace('_',' ')}</span></button>)}</div><div className="mt-5 flex flex-wrap gap-3"><div className="flex min-w-[260px] flex-1 items-center gap-2 rounded-xl border border-white/[.06] bg-black/20 px-3"><Search size={14} className="text-zinc-700"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search artist, studio, room or booking ID" className="w-full bg-transparent py-3 text-xs outline-none placeholder:text-zinc-800"/></div>{status!=='ALL'&&<button onClick={()=>setStatus('ALL')} className="rounded-xl border border-white/[.06] px-4 text-[9px] font-mono text-zinc-600">CLEAR FILTER</button>}</div>
 <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1020px] text-left"><thead><tr className="border-b border-white/[.06] text-[8px] font-mono uppercase tracking-wider text-zinc-700"><th className="pb-3">Session</th><th>Studio</th><th>Schedule</th><th>Value</th><th>Booking state</th><th>Payment</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id} className="border-b border-white/[.04] text-xs"><td className="py-4"><b className="font-medium">{b.artist.alias||b.artist.name}</b><p className="mt-1 text-[9px] text-zinc-700">{b.service} · {b.room}</p></td><td className="text-zinc-500">{b.studio.name}<p className="mt-1 text-[9px] text-zinc-700">{b.engineer||'Unassigned'}</p></td><td className="text-zinc-500">{new Date(b.starts_at).toLocaleDateString()}<p className="mt-1 text-[9px] text-zinc-700">{new Date(b.starts_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p></td><td>${b.total_usd.toLocaleString()}</td><td><span className="rounded-full border px-2 py-1 text-[8px] font-mono" style={{color:statusTone[b.status],borderColor:`${statusTone[b.status]}33`}}>{b.status.replace('_',' ')}</span></td><td><span className={`text-[9px] font-mono ${b.payment?.status==='FAILED'?'text-red-400':b.payment?.status==='PAID'?'text-emerald-400':'text-zinc-600'}`}>{b.payment?.status??'UNPAID'}</span><p className="mt-1 text-[8px] text-zinc-800">{b.payment?.provider??'—'}</p></td></tr>)}</tbody></table>{!bookings.length&&<p className="py-10 text-center text-xs text-zinc-700">No bookings match this view.</p>}</div></article></>}
 </section></main>;
}
