import { ArrowLeft, Building2, CalendarCheck, CircleDollarSign, Eye, Gauge, LogOut, Music2, Search, Settings, Users, Wrench } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import OianoBrand from '../components/OianoBrand';
import ArtistAvatar from '../components/ArtistAvatar';
import { useAuthStore } from '../store/auth.store';
import { api } from '../lib/api';
const SunMark = ({size}:{size:number}) => <OianoBrand variant="icon" size={size}/>;

type Creator={id:string;type:'ARTIST'|'PRODUCER';name:string;alias:string|null;email:string;avatar_url:string|null;created_at:string;status:string;passport_code:string|null;profile_strength:number;profile_views:number;output_count:number;engagement_count:number;completed_count:number};
type Response={totals:{creators:number;artists:number;producers:number;passport_ready:number;engaged:number};average_profile_strength:number;creators:Creator[]};
const items=[{label:'Overview',icon:ArrowLeft,to:'/maintenance'},{label:'Studios',icon:Building2,to:'/maintenance/studios'},{label:'Creators',icon:Users,active:true},{label:'Bookings',icon:CalendarCheck,to:'/maintenance/bookings'},{label:'Finance',icon:CircleDollarSign,to:'/maintenance/finance'},{label:'System health',icon:Wrench,to:'/maintenance/health'}];

export default function MaintenanceCreatorsPage(){
 const navigate=useNavigate(); const {user,logout}=useAuthStore(); const [query,setQuery]=useState(''); const [type,setType]=useState<'ALL'|'ARTIST'|'PRODUCER'>('ALL');
 const {data,isLoading,error}=useQuery<Response>({queryKey:['maintenance-creators'],queryFn:async()=>(await api.get('/maintenance/creators')).data,refetchInterval:60_000});
 const creators=useMemo(()=>data?.creators.filter(c=>(type==='ALL'||c.type===type)&&`${c.name} ${c.alias??''} ${c.email} ${c.passport_code??''}`.toLowerCase().includes(query.toLowerCase()))??[],[data,type,query]);
 return <main className="min-h-screen bg-[#060708] text-white md:pl-[238px]">
  <aside className="fixed inset-y-0 left-0 z-30 hidden w-[238px] flex-col border-r border-white/[.065] bg-[#08090b] md:flex"><div className="flex h-[76px] items-center gap-3 border-b border-white/[.06] px-6"><SunMark size={26}/><div><p className="text-sm font-semibold tracking-[.12em]">OIANO</p><p className="text-[8px] font-mono uppercase tracking-[.22em] text-zinc-600">Maintenance</p></div></div><nav className="flex-1 space-y-1 p-4">{items.map(({label,icon:Icon,to,active})=><button key={label} disabled={!to&&!active} onClick={()=>to&&navigate(to)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-xs ${active?'bg-dome/[.1] text-dome':'text-zinc-600 hover:bg-white/[.025] hover:text-zinc-400 disabled:cursor-default'}`}><Icon size={15}/>{label}{active&&<i className="ml-auto h-1.5 w-1.5 rounded-full bg-dome"/>}</button>)}</nav><p className="truncate border-t border-white/[.06] p-7 text-[9px] text-zinc-800">{user?.email}</p></aside>
  <header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-white/[.065] bg-[#060708]/90 px-5 backdrop-blur-xl md:px-8"><button onClick={()=>navigate('/maintenance')} className="flex items-center gap-2 text-xs text-zinc-600 hover:text-white"><ArrowLeft size={14}/> Network overview</button><div className="flex gap-2"><button className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.06] text-zinc-600"><Settings size={15}/></button><button onClick={()=>{logout();navigate('/enter')}} className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.06] text-zinc-600"><LogOut size={15}/></button></div></header>
  <section className="mx-auto max-w-[1380px] px-5 py-10 md:px-8"><div><p className="mb-3 text-[9px] font-mono uppercase tracking-[.28em] text-[#C9A84C]">Network · Creators</p><h1 className="font-display text-4xl">The creative economy, visible.</h1><p className="mt-3 text-sm text-zinc-600">Growth and professional readiness without exposing private creative work.</p></div>
  {isLoading?<p className="mt-12 text-xs text-zinc-700">Reading creator activity…</p>:error||!data?<div role="alert" className="mt-10 rounded-xl border border-red-500/20 p-5 text-red-300">Creator intelligence is unavailable.</div>:<><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[Users,'Creators',data.totals.creators],[Music2,'Artists',data.totals.artists],[Gauge,'Producers',data.totals.producers],[Gauge,'Average profile',`${data.average_profile_strength}%`],[CalendarCheck,'Engaged',data.totals.engaged]].map(([Icon,label,value]:any)=><article key={label} className="rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-5"><Icon size={15} className="text-[#C9A84C]"/><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-mono uppercase tracking-wider text-zinc-600">{label}</p></article>)}</div>
  <article className="mt-3 rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex min-w-[240px] flex-1 items-center gap-2 rounded-xl border border-white/[.06] bg-black/20 px-3"><Search size={14} className="text-zinc-700"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search creator, email or Passport" className="w-full bg-transparent py-3 text-xs text-white outline-none placeholder:text-zinc-800"/></div><div className="flex rounded-xl border border-white/[.06] p-1">{(['ALL','ARTIST','PRODUCER'] as const).map(value=><button key={value} onClick={()=>setType(value)} className={`rounded-lg px-3 py-2 text-[9px] font-mono ${type===value?'bg-white/[.08] text-white':'text-zinc-700'}`}>{value}</button>)}</div></div>
  <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-white/[.06] text-[8px] font-mono uppercase tracking-[.14em] text-zinc-700"><th className="pb-3">Creator</th><th>Passport readiness</th><th>Engagement</th><th>Public reach</th><th>Status</th><th>Joined</th></tr></thead><tbody>{creators.map(c=><tr key={`${c.type}-${c.id}`} className="border-b border-white/[.04] text-xs"><td className="py-4"><div className="flex items-center gap-3"><ArtistAvatar name={c.name} src={c.avatar_url} size={36}/><div><b className="font-medium">{c.alias||c.name}</b><p className="mt-1 text-[9px] text-zinc-700">{c.type} · {c.email}</p></div></div></td><td><div className="flex items-center gap-3"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-white/[.05]"><i className="block h-full rounded-full bg-dome" style={{width:`${c.profile_strength}%`}}/></div><span className="text-[10px] text-zinc-500">{c.profile_strength}%</span></div></td><td className="text-zinc-500">{c.engagement_count} {c.type==='ARTIST'?'bookings':'projects'}<p className="mt-1 text-[9px] text-zinc-700">{c.output_count} {c.type==='ARTIST'?'releases':'active tracks'}</p></td><td><span className="flex items-center gap-1 text-zinc-500"><Eye size={11}/>{c.profile_views}</span></td><td><span className="rounded-full border border-emerald-500/15 bg-emerald-500/[.04] px-2 py-1 text-[8px] font-mono text-emerald-500">{c.status.replace(/_/g,' ')}</span></td><td className="text-[10px] text-zinc-700">{new Date(c.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!creators.length&&<p className="py-10 text-center text-xs text-zinc-700">No creators match this view.</p>}</div></article></>}
  </section>
 </main>;
}
