import { Building2, CircleDollarSign, DoorOpen, MapPin, Radio, Users } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../lib/api';
import MaintenanceShell from '../components/MaintenanceShell';

type Studio = { id:string; slug:string; name:string; address:string|null; timezone:string; currency:string; email:string|null; operator:string|null; rooms:Array<{id:string;name:string}>; engineers:Array<{id:string;name:string}>; team_count:number; booking_count:number; bookings_30d:number; completed_bookings:number; live_sessions:number; paid_volume:number; status:'LIVE'|'ONLINE' };

export default function MaintenanceStudiosPage(){
  const {data=[],isLoading,error}=useQuery<Studio[]>({queryKey:['maintenance-studios'],queryFn:async()=>(await api.get('/maintenance/studios')).data,refetchInterval:60_000});
  const totals=data.reduce((a,s)=>({rooms:a.rooms+s.rooms.length,team:a.team+s.team_count,bookings:a.bookings+s.booking_count,volume:a.volume+s.paid_volume}),{rooms:0,team:0,bookings:0,volume:0});
  return <MaintenanceShell>
    <section className="mx-auto max-w-[1380px] px-5 py-10 md:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-[9px] font-mono uppercase tracking-[.28em] text-dome">Network · Studios</p><h1 className="font-display text-4xl">Every studio, accountable.</h1><p className="mt-3 text-sm text-zinc-600">Operational and commercial health across the OIANO studio network.</p></div><span className="flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/[.05] px-3 py-1.5 text-[9px] font-mono uppercase text-emerald-400"><Radio size={10}/>{data.length} online</span></div>
      {isLoading?<p className="mt-12 text-xs text-zinc-700">Reading studios…</p>:error?<div role="alert" className="mt-10 rounded-xl border border-red-500/20 p-5 text-red-300">Studio intelligence is unavailable.</div>:<><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[Building2,'Studios',data.length],[DoorOpen,'Rooms',totals.rooms],[Users,'Studio team',totals.team],[CircleDollarSign,'Paid volume',`$${totals.volume.toLocaleString()}`]].map(([Icon,label,value]:any)=><div key={label} className="metric-enter rounded-2xl border border-white/[.065] bg-studio-surface p-5"><Icon size={15} className="text-dome"/><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-mono uppercase tracking-wider text-zinc-600">{label}</p></div>)}</div>
      <div className="mt-3 grid gap-3 xl:grid-cols-2">{data.map(studio=><article key={studio.id} className="rounded-2xl border border-white/[.065] bg-studio-surface p-6"><div className="flex items-start justify-between gap-4"><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-dome/15 bg-dome/[.06]"><Building2 size={18} className="text-dome"/></div><div><div className="flex items-center gap-2"><h2 className="text-base font-semibold">{studio.name}</h2>{studio.status==='LIVE'&&<span className="rounded-full bg-red-500/10 px-2 py-0.5 text-[8px] font-mono text-red-400">LIVE</span>}</div><p className="mt-1 flex items-center gap-1 text-[10px] text-zinc-700"><MapPin size={10}/>{studio.address||'Address not configured'}</p></div></div><span className="text-[9px] font-mono text-emerald-500">● ONLINE</span></div><div className="mt-7 grid grid-cols-4 gap-3 border-y border-white/[.05] py-5 text-center"><div><b>{studio.rooms.length}</b><p>Rooms</p></div><div><b>{studio.team_count}</b><p>Team</p></div><div><b>{studio.booking_count}</b><p>Bookings</p></div><div><b>${studio.paid_volume.toLocaleString()}</b><p>Paid</p></div></div><style>{`article div.grid.grid-cols-4 p{margin-top:4px;font-size:8px;text-transform:uppercase;letter-spacing:.1em;color:#3f3f46}`}</style><div className="mt-5 grid gap-3 text-[10px] sm:grid-cols-2"><p className="text-zinc-700">Studio Operator<br/><span className="mt-1 block text-zinc-400">{studio.operator||'Not assigned'}</span></p><p className="text-zinc-700">Recent activity<br/><span className="mt-1 block text-zinc-400">{studio.bookings_30d} bookings in 30 days · {studio.live_sessions} live</span></p></div></article>)}</div></>}
    </section>
  </MaintenanceShell>;
}
