import { CalendarCheck, Eye, Gauge, Music2, Users } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import ArtistAvatar from '../components/ArtistAvatar';
import { api } from '../lib/api';
import MaintenanceShell from '../components/MaintenanceShell';
import SearchInput from '../components/SearchInput';

type Creator={id:string;type:'ARTIST'|'PRODUCER';name:string;alias:string|null;email:string;avatar_url:string|null;created_at:string;status:string;passport_code:string|null;profile_strength:number;profile_views:number;output_count:number;engagement_count:number;completed_count:number};
type Response={totals:{creators:number;artists:number;producers:number;passport_ready:number;engaged:number};average_profile_strength:number;creators:Creator[]};

export default function MaintenanceCreatorsPage(){
 const [query,setQuery]=useState(''); const [type,setType]=useState<'ALL'|'ARTIST'|'PRODUCER'>('ALL');
 const {data,isLoading,error}=useQuery<Response>({queryKey:['maintenance-creators'],queryFn:async()=>(await api.get('/maintenance/creators')).data,refetchInterval:60_000});
 const creators=useMemo(()=>data?.creators.filter(c=>(type==='ALL'||c.type===type)&&`${c.name} ${c.alias??''} ${c.email} ${c.passport_code??''}`.toLowerCase().includes(query.toLowerCase()))??[],[data,type,query]);
 return <MaintenanceShell>
  <section className="mx-auto max-w-[1380px] px-5 py-10 md:px-8"><div><p className="mb-3 text-[9px] font-mono uppercase tracking-[.28em] text-[#C9A84C]">Network · Creators</p><h1 className="font-display text-4xl">The creative economy, visible.</h1><p className="mt-3 text-sm text-zinc-600">Growth and professional readiness without exposing private creative work.</p></div>
  {isLoading?<p className="mt-12 text-xs text-zinc-700">Reading creator activity…</p>:error||!data?<div role="alert" className="mt-10 rounded-xl border border-red-500/20 p-5 text-red-300">Creator intelligence is unavailable.</div>:<><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[Users,'Creators',data.totals.creators],[Music2,'Artists',data.totals.artists],[Gauge,'Producers',data.totals.producers],[Gauge,'Average profile',`${data.average_profile_strength}%`],[CalendarCheck,'Engaged',data.totals.engaged]].map(([Icon,label,value]:any)=><article key={label} className="metric-enter rounded-2xl border border-white/[.065] bg-studio-surface p-5"><Icon size={15} className="text-[#C9A84C]"/><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-mono uppercase tracking-wider text-zinc-600">{label}</p></article>)}</div>
  <article className="mt-3 rounded-2xl border border-white/[.065] bg-studio-surface p-5"><div className="flex flex-wrap items-center justify-between gap-3"><SearchInput value={query} onChange={setQuery} placeholder="Search creator, email or Passport" className="min-w-[240px] flex-1" /><div className="flex rounded-xl border border-white/[.06] p-1">{(['ALL','ARTIST','PRODUCER'] as const).map(value=><button key={value} onClick={()=>setType(value)} className={`rounded-lg px-3 py-2 text-[9px] font-mono ${type===value?'bg-white/[.08] text-white':'text-zinc-700'}`}>{value}</button>)}</div></div>
  <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-white/[.06] text-[8px] font-mono uppercase tracking-[.14em] text-zinc-700"><th className="pb-3">Creator</th><th>Passport readiness</th><th>Engagement</th><th>Public reach</th><th>Status</th><th>Joined</th></tr></thead><tbody>{creators.map(c=><tr key={`${c.type}-${c.id}`} className="border-b border-white/[.04] text-xs"><td className="py-4"><div className="flex items-center gap-3"><ArtistAvatar name={c.name} src={c.avatar_url} size={36}/><div><b className="font-medium">{c.alias||c.name}</b><p className="mt-1 text-[9px] text-zinc-700">{c.type} · {c.email}</p></div></div></td><td><div className="flex items-center gap-3"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-white/[.05]"><i className="block h-full rounded-full bg-dome" style={{width:`${c.profile_strength}%`}}/></div><span className="text-[10px] text-zinc-500">{c.profile_strength}%</span></div></td><td className="text-zinc-500">{c.engagement_count} {c.type==='ARTIST'?'bookings':'projects'}<p className="mt-1 text-[9px] text-zinc-700">{c.output_count} {c.type==='ARTIST'?'releases':'active tracks'}</p></td><td><span className="flex items-center gap-1 text-zinc-500"><Eye size={11}/>{c.profile_views}</span></td><td><span className="rounded-full border border-emerald-500/15 bg-emerald-500/[.04] px-2 py-1 text-[8px] font-mono text-emerald-500">{c.status.replace(/_/g,' ')}</span></td><td className="text-[10px] text-zinc-700">{new Date(c.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!creators.length&&<p className="py-10 text-center text-xs text-zinc-700">No creators match this view.</p>}</div></article></>}
  </section>
 </MaintenanceShell>;
}
