import { AlertTriangle, Building2, CheckCircle2, KeyRound, Mail, ShieldCheck, UserCog } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import MaintenanceShell from '../components/MaintenanceShell';
import { api } from '../lib/api';

type Data={totals:{studios:number;operators:number;covered_studios:number;unassigned_studios:number;mfa_enabled:number};operators:Array<{id:string;email:string;joined_at:string;mfa_enabled:boolean;studio:{id:string;name:string;slug:string}}>;studios:Array<{id:string;name:string;slug:string;email:string|null;rooms:number;active_bookings:number;operator_assigned:boolean}>;capabilities:{invitations:boolean;last_login_tracking:boolean;operator_mfa_enforcement:boolean}};

export default function MaintenanceOperatorsPage(){
 const{data,isLoading,error}=useQuery<Data>({queryKey:['maintenance-operators'],queryFn:async()=>(await api.get('/maintenance/operators')).data,refetchInterval:60_000});
 return <MaintenanceShell><section className="mx-auto max-w-[1380px] px-5 py-10 md:px-8"><p className="mb-3 text-[9px] font-mono uppercase tracking-[.28em] text-dome">Network · Studio Operators</p><h1 className="font-display text-4xl">Clear ownership at every studio.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-600">Accountability, coverage and security posture for the people operating OIANO studios.</p>
 {isLoading?<p className="mt-12 text-xs text-zinc-700">Reading operator coverage…</p>:error||!data?<div role="alert" className="mt-10 rounded-xl border border-red-500/20 p-5 text-red-300">Operator intelligence is unavailable.</div>:<><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[Building2,'Studios',data.totals.studios],[UserCog,'Operators',data.totals.operators],[CheckCircle2,'Covered',data.totals.covered_studios],[AlertTriangle,'Unassigned',data.totals.unassigned_studios],[ShieldCheck,'MFA enabled',data.totals.mfa_enabled]].map(([Icon,label,value]:any)=><article key={label} className="rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-5"><Icon size={15} className={label==='Unassigned'&&value?'text-amber-400':'text-dome'}/><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-mono uppercase tracking-wider text-zinc-600">{label}</p></article>)}</div>
 <div className="mt-3 grid gap-3 xl:grid-cols-[1.25fr_1fr]"><article className="rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Operator directory</h2><p className="mt-1 text-xs text-zinc-700">Accountable studio owners and managers</p></div><UserCog size={16} className="text-dome"/></div><div className="mt-6 space-y-2">{data.operators.map(operator=><div key={operator.id} className="flex flex-wrap items-center gap-4 rounded-xl border border-white/[.05] p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-dome/[.07]"><UserCog size={16} className="text-dome"/></div><div className="min-w-0 flex-1"><b className="block truncate text-xs">{operator.email}</b><p className="mt-1 text-[9px] text-zinc-700">{operator.studio.name} · Since {new Date(operator.joined_at).toLocaleDateString()}</p></div><span className={`flex items-center gap-1 rounded-full border px-2 py-1 text-[8px] font-mono ${operator.mfa_enabled?'border-emerald-500/15 text-emerald-500':'border-amber-500/15 text-amber-400'}`}><KeyRound size={9}/>{operator.mfa_enabled?'MFA ACTIVE':'MFA REQUIRED'}</span></div>)}{!data.operators.length&&<p className="text-xs text-zinc-700">No Studio Operators assigned.</p>}</div></article>
 <article className="rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-6"><h2 className="text-sm font-semibold">Coverage by studio</h2><p className="mt-1 text-xs text-zinc-700">Every location needs one accountable Operator</p><div className="mt-6 space-y-2">{data.studios.map(studio=><div key={studio.id} className="rounded-xl border border-white/[.05] p-4"><div className="flex items-center justify-between"><b className="text-xs">{studio.name}</b><span className={studio.operator_assigned?'text-emerald-500':'text-amber-400'}>{studio.operator_assigned?'● COVERED':'● UNASSIGNED'}</span></div><p className="mt-2 text-[9px] text-zinc-700">{studio.rooms} rooms · {studio.active_bookings} active bookings</p>{studio.email&&<p className="mt-2 flex items-center gap-1 text-[9px] text-zinc-600"><Mail size={9}/>{studio.email}</p>}</div>)}</div></article></div>
 <div className="mt-3 rounded-2xl border border-amber-500/10 bg-amber-500/[.025] p-5"><p className="flex items-center gap-2 text-xs text-amber-400"><AlertTriangle size={14}/>Operator governance still needs invitation and access lifecycle controls</p><p className="mt-2 text-[10px] leading-5 text-zinc-700">Next infrastructure: secure invitations, last-login visibility, mandatory Operator MFA, suspension and reassignment with audit events.</p></div></>}
 </section></MaintenanceShell>;
}
