import { ArrowLeft, Building2, CalendarCheck, CircleDollarSign, DoorOpen, LogOut, MapPin, Radio, Settings, Users, Wrench } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import OianoBrand from '../components/OianoBrand';
import { useAuthStore } from '../store/auth.store';
import { api } from '../lib/api';
const SunMark = ({size}:{size:number}) => <OianoBrand variant="icon" size={size}/>;

type Studio = { id:string; slug:string; name:string; address:string|null; timezone:string; currency:string; email:string|null; operator:string|null; rooms:Array<{id:string;name:string}>; engineers:Array<{id:string;name:string}>; team_count:number; booking_count:number; bookings_30d:number; completed_bookings:number; live_sessions:number; paid_volume:number; status:'LIVE'|'ONLINE' };

const items = [{label:'Overview',icon:ArrowLeft,to:'/maintenance'},{label:'Studios',icon:Building2,active:true},{label:'Creators',icon:Users,to:'/maintenance/creators'},{label:'Bookings',icon:CalendarCheck,to:'/maintenance/bookings'},{label:'Finance',icon:CircleDollarSign,to:'/maintenance/finance'},{label:'System health',icon:Wrench,to:'/maintenance/health'}];

export default function MaintenanceStudiosPage(){
  const navigate=useNavigate(); const {user,logout}=useAuthStore();
  const {data=[],isLoading,error}=useQuery<Studio[]>({queryKey:['maintenance-studios'],queryFn:async()=>(await api.get('/maintenance/studios')).data,refetchInterval:60_000});
  const totals=data.reduce((a,s)=>({rooms:a.rooms+s.rooms.length,team:a.team+s.team_count,bookings:a.bookings+s.booking_count,volume:a.volume+s.paid_volume}),{rooms:0,team:0,bookings:0,volume:0});
  return <main className="min-h-screen bg-[#060708] text-white md:pl-[238px]">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-[238px] flex-col border-r border-white/[.065] bg-[#08090b] md:flex"><div className="flex h-[76px] items-center gap-3 border-b border-white/[.06] px-6"><SunMark size={26}/><div><p className="text-sm font-semibold tracking-[.12em]">OIANO</p><p className="text-[8px] font-mono uppercase tracking-[.22em] text-zinc-600">Maintenance</p></div></div><nav className="flex-1 space-y-1 p-4">{items.map(({label,icon:Icon,to,active})=><button key={label} disabled={!to&&!active} onClick={()=>to&&navigate(to)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-xs ${active?'bg-dome/[.1] text-dome':'text-zinc-600 hover:bg-white/[.025] hover:text-zinc-400 disabled:cursor-default'}`}><Icon size={15}/>{label}{active&&<i className="ml-auto h-1.5 w-1.5 rounded-full bg-dome"/>}</button>)}</nav><div className="border-t border-white/[.06] p-4"><p className="truncate px-3 text-[9px] text-zinc-800">{user?.email}</p></div></aside>
    <header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-white/[.065] bg-[#060708]/90 px-5 backdrop-blur-xl md:px-8"><button onClick={()=>navigate('/maintenance')} className="flex items-center gap-2 text-xs text-zinc-600 hover:text-white"><ArrowLeft size={14}/> Network overview</button><div className="flex gap-2"><button className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.06] text-zinc-600"><Settings size={15}/></button><button onClick={()=>{logout();navigate('/enter')}} className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.06] text-zinc-600"><LogOut size={15}/></button></div></header>
    <section className="mx-auto max-w-[1380px] px-5 py-10 md:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-[9px] font-mono uppercase tracking-[.28em] text-dome">Network · Studios</p><h1 className="font-display text-4xl">Every studio, accountable.</h1><p className="mt-3 text-sm text-zinc-600">Operational and commercial health across the OIANO studio network.</p></div><span className="flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/[.05] px-3 py-1.5 text-[9px] font-mono uppercase text-emerald-400"><Radio size={10}/>{data.length} online</span></div>
      {isLoading?<p className="mt-12 text-xs text-zinc-700">Reading studios…</p>:error?<div role="alert" className="mt-10 rounded-xl border border-red-500/20 p-5 text-red-300">Studio intelligence is unavailable.</div>:<><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[Building2,'Studios',data.length],[DoorOpen,'Rooms',totals.rooms],[Users,'Studio team',totals.team],[CircleDollarSign,'Paid volume',`$${totals.volume.toLocaleString()}`]].map(([Icon,label,value]:any)=><div key={label} className="rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-5"><Icon size={15} className="text-dome"/><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-mono uppercase tracking-wider text-zinc-600">{label}</p></div>)}</div>
      <div className="mt-3 grid gap-3 xl:grid-cols-2">{data.map(studio=><article key={studio.id} className="rounded-2xl border border-white/[.065] bg-[#0b0d0f] p-6"><div className="flex items-start justify-between gap-4"><div className="flex gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-dome/15 bg-dome/[.06]"><Building2 size={18} className="text-dome"/></div><div><div className="flex items-center gap-2"><h2 className="text-base font-semibold">{studio.name}</h2>{studio.status==='LIVE'&&<span className="rounded-full bg-red-500/10 px-2 py-0.5 text-[8px] font-mono text-red-400">LIVE</span>}</div><p className="mt-1 flex items-center gap-1 text-[10px] text-zinc-700"><MapPin size={10}/>{studio.address||'Address not configured'}</p></div></div><span className="text-[9px] font-mono text-emerald-500">● ONLINE</span></div><div className="mt-7 grid grid-cols-4 gap-3 border-y border-white/[.05] py-5 text-center"><div><b>{studio.rooms.length}</b><p>Rooms</p></div><div><b>{studio.team_count}</b><p>Team</p></div><div><b>{studio.booking_count}</b><p>Bookings</p></div><div><b>${studio.paid_volume.toLocaleString()}</b><p>Paid</p></div></div><style>{`article div.grid.grid-cols-4 p{margin-top:4px;font-size:8px;text-transform:uppercase;letter-spacing:.1em;color:#3f3f46}`}</style><div className="mt-5 grid gap-3 text-[10px] sm:grid-cols-2"><p className="text-zinc-700">Studio Operator<br/><span className="mt-1 block text-zinc-400">{studio.operator||'Not assigned'}</span></p><p className="text-zinc-700">Recent activity<br/><span className="mt-1 block text-zinc-400">{studio.bookings_30d} bookings in 30 days · {studio.live_sessions} live</span></p></div></article>)}</div></>}
    </section>
  </main>;
}
