import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { ArrowLeft, KeyRound, ShieldCheck, Trash2, UserPlus, Users } from 'lucide-react';
import { api } from '../lib/api';
import { useToast } from '../components/Toast';

const POSITION_PRESETS: Record<string,{role:'STUDIO_ADMIN'|'ENGINEER';capabilities:string[]}>={
  OWNER:{role:'STUDIO_ADMIN',capabilities:['MANAGE_BOOKINGS','MANAGE_CALENDAR','MANAGE_STAFF','MANAGE_POLICIES','VIEW_FINANCE','POLICY_OVERRIDE_ALL']},
  MANAGER:{role:'STUDIO_ADMIN',capabilities:['MANAGE_BOOKINGS','MANAGE_CALENDAR','MANAGE_STAFF','MANAGE_POLICIES','VIEW_FINANCE']},
  RECEPTION:{role:'STUDIO_ADMIN',capabilities:['VIEW_CALENDAR','MANAGE_CALENDAR','MANAGE_BOOKINGS']},
  ENGINEER:{role:'ENGINEER',capabilities:['VIEW_CALENDAR','MANAGE_ASSIGNED_SESSIONS','UPLOAD_DELIVERABLES']},
  PRODUCER:{role:'ENGINEER',capabilities:['VIEW_CALENDAR','MANAGE_ASSIGNED_SESSIONS','UPLOAD_DELIVERABLES']},
};
type TeamData={studio:{id:string;name:string};capabilities:string[];members:any[];invitations:any[]};

export default function StudioTeamPage(){
  const qc=useQueryClient();const toast=useToast();const[email,setEmail]=useState('');const[position,setPosition]=useState('ENGINEER');
  const preset=useMemo(()=>POSITION_PRESETS[position]??POSITION_PRESETS.ENGINEER,[position]);
  const{data,isLoading}=useQuery<TeamData>({queryKey:['studio-team'],queryFn:async()=>(await api.get('/studio/team')).data});
  const invite=useMutation({mutationFn:()=>api.post('/studio/team/invitations',{email,position,role:preset.role,capabilities:preset.capabilities}),onSuccess:()=>{setEmail('');qc.invalidateQueries({queryKey:['studio-team']});toast.success('Secure invitation created')},onError:(e:any)=>toast.error(e?.response?.data?.error??'Invitation failed')});
  const revokeInvite=useMutation({mutationFn:(id:string)=>api.delete(`/studio/team/invitations/${id}`),onSuccess:()=>qc.invalidateQueries({queryKey:['studio-team']})});
  const removeMember=useMutation({mutationFn:(id:string)=>api.delete(`/studio/team/${id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:['studio-team']});toast.success('Studio access revoked')},onError:(e:any)=>toast.error(e?.response?.data?.error??'Access could not be revoked')});
  return <main className="min-h-screen bg-studio-bg px-4 py-8 text-white md:px-8"><div className="mx-auto max-w-6xl">
    <Link to="/admin" className="inline-flex items-center gap-2 text-[10px] text-zinc-600 hover:text-white"><ArrowLeft size={13}/>Operator dashboard</Link>
    <div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-mono uppercase tracking-[.25em] text-dome">People & authority</p><h1 className="mt-3 font-display text-4xl">Studio team</h1><p className="mt-3 max-w-xl text-xs leading-5 text-zinc-500">Every person receives a studio-specific position and only the capabilities their work requires.</p></div><div className="rounded-full border border-emerald-500/15 px-3 py-1.5 text-[9px] text-emerald-400"><ShieldCheck size={11} className="mr-2 inline"/>Audited access</div></div>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1fr_.8fr]"><article className="card-lift rounded-2xl border border-white/[.07] bg-studio-surface p-5"><div className="flex items-center gap-2"><Users size={15} className="text-dome"/><h2 className="text-sm">{data?.studio.name??'Studio'} team</h2></div><div className="mt-5 space-y-3">{isLoading?<div className="h-24 animate-pulse rounded-xl bg-white/[.03]"/>:data?.members.map(member=><div key={member.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-white/[.055] bg-black/20 p-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-white/[.04] text-xs">{member.user.email[0].toUpperCase()}</div><div className="min-w-0 flex-1"><b className="block truncate text-xs">{member.user.email}</b><p className="mt-1 text-[9px] uppercase tracking-wider text-zinc-600">{member.position.replaceAll('_',' ')} · {member.capabilities.length} capabilities</p></div><span className={`inline-flex items-center gap-1.5 rounded-full border px-2 py-1 text-[8px] ${member.user.mfa_enabled?'border-emerald-500/20 text-emerald-400':'border-amber-500/20 text-amber-400'}`}><span className="signal-dot" style={{ '--signal': member.user.mfa_enabled ? '#34d399' : '#fbbf24', width: 5, height: 5 } as React.CSSProperties} />{member.user.mfa_enabled?'MFA ON':'MFA OFF'}</span><button onClick={()=>confirm('Revoke this studio membership?')&&removeMember.mutate(member.id)} aria-label="Revoke access" className="rounded-lg p-2 text-zinc-700 hover:bg-red-500/10 hover:text-red-400"><Trash2 size={14}/></button></div>)}</div></article>
      <article className="card-lift rounded-2xl border border-white/[.07] bg-studio-surface p-5"><div className="flex items-center gap-2"><UserPlus size={15} className="text-[#6aa9d2]"/><h2 className="text-sm">Invite team member</h2></div><label className="mt-5 block text-[8px] uppercase tracking-wider text-zinc-600">Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" className="mt-2 w-full rounded-xl border border-white/[.08] bg-black/30 px-4 py-3 text-xs text-white outline-none focus:border-[#6aa9d2]/50"/></label><label className="mt-4 block text-[8px] uppercase tracking-wider text-zinc-600">Position<select value={position} onChange={e=>setPosition(e.target.value)} className="mt-2 w-full rounded-xl border border-white/[.08] bg-[#0a0b0c] px-4 py-3 text-xs text-white">{Object.keys(POSITION_PRESETS).map(p=><option key={p}>{p}</option>)}</select></label><div className="mt-4 rounded-xl bg-black/25 p-4"><p className="flex items-center gap-2 text-[9px] text-zinc-500"><KeyRound size={11}/>Granted capabilities</p><div className="mt-3 flex flex-wrap gap-1.5">{preset.capabilities.map(c=><span key={c} className="rounded-full border border-white/[.06] px-2 py-1 text-[7px] text-zinc-600">{c.replaceAll('_',' ')}</span>)}</div></div><button disabled={!email||invite.isPending} onClick={()=>invite.mutate()} className="mt-5 w-full rounded-xl bg-[#6aa9d2] px-4 py-3 text-xs font-semibold text-[#071016] disabled:opacity-40">{invite.isPending?'Creating invitation…':'Send secure invitation'}</button></article>
    </section>
    {!!data?.invitations.length&&<section className="mt-5 rounded-2xl border border-white/[.06] bg-studio-surface p-5"><h2 className="text-xs">Pending invitations</h2><div className="mt-4 divide-y divide-white/[.05]">{data.invitations.map(inv=><div key={inv.id} className="flex items-center gap-3 py-3 text-xs"><span className="flex-1 text-zinc-400">{inv.email}<small className="ml-2 text-zinc-700">{inv.position.replaceAll('_',' ')}</small></span><span className="text-[8px] text-zinc-700">Expires {new Date(inv.expires_at).toLocaleDateString()}</span><button onClick={()=>revokeInvite.mutate(inv.id)} className="text-[9px] text-red-400">Revoke</button></div>)}</div></section>}
  </div></main>;
}
