import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, Check, FileClock, Plus, ShieldCheck, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import { useToast } from '../components/Toast';

type Policy = { id:string; domain:string; subject:string; name:string; description?:string|null; enforcement:string; override_capability?:string|null; version:number; status:string; default_outcome:any };
type Exception = { id:string; status:string; target_type:string; target_id:string; reason:string; normal_values:any; requested_values:any; consequence:any; created_at:string; policy:Policy; requester:{email:string}; approver?:{email:string}|null };
const templates = {
  DEPOSIT: { domain:'PAYMENT', subject:'BOOKING_DEPOSIT', name:'Standard booking deposit', field:'payment.deposit_percent', operator:'GTE', value:50, capability:'WAIVE_DEPOSIT', consequence:'Outstanding balance remains on the booking.' },
  PRICE: { domain:'PRICING', subject:'STANDARD_RATE', name:'Minimum approved rate', field:'pricing.hourly_rate', operator:'GTE', value:30, capability:'CHANGE_PRICE', consequence:'Revenue will be below the standard rate.' },
  HOURS: { domain:'BOOKING', subject:'CLOSING_TIME', name:'Studio closing time', field:'booking.end_hour', operator:'LTE', value:23, capability:'EXTEND_HOURS', consequence:'The session will operate outside normal opening hours.' },
} as const;

export default function StudioPoliciesPage(){
  const qc=useQueryClient(); const toast=useToast(); const [showCreate,setShowCreate]=useState(false); const [template,setTemplate]=useState<keyof typeof templates>('DEPOSIT'); const [value,setValue]=useState(50);
  const {data:policies=[],isLoading,isError}=useQuery<Policy[]>({queryKey:['studio-policies'],queryFn:async()=>(await api.get('/studio-policies')).data});
  const {data:exceptions=[]}=useQuery<Exception[]>({queryKey:['studio-policy-exceptions'],queryFn:async()=>(await api.get('/studio-policies/exceptions')).data});
  const create=useMutation({mutationFn:async()=>{const t=templates[template];return api.post('/studio-policies',{domain:t.domain,subject:t.subject,name:t.name,conditions:{},default_outcome:{requirements:[{field:t.field,operator:t.operator,value}],consequence:{summary:t.consequence}},enforcement:'CONTROLLED',override_capability:t.capability})},onSuccess:()=>{qc.invalidateQueries({queryKey:['studio-policies']});setShowCreate(false);toast.success('Studio policy activated')},onError:(e:any)=>toast.error(e?.response?.data?.error??'Policy could not be created')});
  const decide=useMutation({mutationFn:({id,decision}:{id:string;decision:'APPROVE'|'REJECT'|'ESCALATE'})=>api.patch(`/studio-policies/exceptions/${id}/decision`,{decision}),onSuccess:()=>{qc.invalidateQueries({queryKey:['studio-policy-exceptions']});toast.success('Exception decision recorded')},onError:(e:any)=>toast.error(e?.response?.data?.error??'Decision could not be recorded')});
  const active=policies.filter(p=>p.status==='ACTIVE'); const waiting=exceptions.filter(e=>e.status==='REQUESTED'||e.status==='ESCALATED');
  return <main className="min-h-screen bg-[#07090b] px-5 py-8 text-zinc-100 md:px-8"><div className="mx-auto max-w-7xl">
    <header className="border-b border-white/[.07] pb-8"><Link to="/admin" className="inline-flex items-center gap-2 text-[9px] font-mono uppercase tracking-wider text-zinc-600 no-underline hover:text-white"><ArrowLeft size={12}/>Studio command centre</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-5"><div><p className="text-[9px] font-mono uppercase tracking-[.25em] text-dome">Operating standards</p><h1 className="mt-3 font-display text-4xl md:text-5xl">Structure without losing judgement.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-500">Set the normal way your studio works, then approve accountable exceptions without weakening the original rule.</p></div><button type="button" onClick={()=>setShowCreate(true)} className="inline-flex items-center gap-2 rounded-xl bg-dome px-4 py-3 text-xs font-semibold text-black"><Plus size={14}/>New policy</button></div></header>
    <section aria-label="Policy control summary" className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4"><article className="rounded-2xl border border-white/[.06] bg-[#0c0f12] p-4"><ShieldCheck size={15} className="text-dome"/><p className="mt-4 text-2xl">{active.length}</p><p className="text-[8px] uppercase text-zinc-700">Active standards</p></article><article className="rounded-2xl border border-white/[.06] bg-[#0c0f12] p-4"><FileClock size={15} className="text-amber-300"/><p className="mt-4 text-2xl">{waiting.length}</p><p className="text-[8px] uppercase text-zinc-700">Awaiting decision</p></article><article className="col-span-2 rounded-2xl border border-emerald-400/10 bg-emerald-400/[.025] p-4"><p className="text-[9px] font-mono uppercase text-emerald-400">Control principle</p><p className="mt-3 text-xs leading-5 text-zinc-500">Rules establish consistency. Exceptions preserve human judgement. OIANO records both.</p></article></section>
    {showCreate&&<section className="mt-6 rounded-3xl border border-dome/20 bg-[#0c0f12] p-6" aria-labelledby="new-policy"><div className="flex justify-between gap-4"><div><h2 id="new-policy" className="text-lg font-semibold">Activate a studio standard</h2><p className="mt-1 text-xs text-zinc-600">Start with a controlled operational template. Later versions replace the active default without rewriting history.</p></div><button type="button" aria-label="Close policy form" onClick={()=>setShowCreate(false)}><X size={16}/></button></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-[9px] uppercase text-zinc-500">Policy template<select value={template} onChange={e=>{const key=e.target.value as keyof typeof templates;setTemplate(key);setValue(templates[key].value)}} className="mt-2 w-full rounded-xl border border-white/[.08] bg-black/30 p-3 text-xs text-white"><option value="DEPOSIT">Booking deposit</option><option value="PRICE">Minimum rate</option><option value="HOURS">Closing time</option></select></label><label className="text-[9px] uppercase text-zinc-500">Required value<input type="number" value={value} onChange={e=>setValue(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-white/[.08] bg-black/30 p-3 text-xs text-white"/></label><div className="self-end"><button type="button" disabled={create.isPending} onClick={()=>create.mutate()} className="w-full rounded-xl bg-dome p-3 text-xs font-semibold text-black disabled:opacity-40">{create.isPending?'Activating…':'Activate policy'}</button></div></div></section>}
    {isError&&<div role="alert" className="mt-6 rounded-2xl border border-red-400/15 bg-red-400/[.03] p-5 text-sm text-red-300">Policy controls are unavailable until the studio-policy database migration is applied.</div>}
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_.9fr]"><section><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-dome"/><h2 className="text-xs font-semibold uppercase tracking-wider">Active policies</h2></div><div className="mt-4 space-y-3">{isLoading?<div className="h-32 animate-pulse rounded-2xl bg-white/[.03]"/>:active.map(p=><article key={p.id} className="rounded-2xl border border-white/[.06] bg-[#0c0f12] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[8px] font-mono uppercase tracking-wider text-dome">{p.domain} · {p.subject.replaceAll('_',' ')}</p><h3 className="mt-2 text-sm font-semibold">{p.name}</h3><p className="mt-2 text-[10px] text-zinc-600">Version {p.version} · {p.enforcement.toLowerCase()} enforcement</p></div><span className="rounded-full border border-emerald-400/15 px-2 py-1 text-[7px] uppercase text-emerald-400">Active</span></div><p className="mt-4 text-[9px] text-zinc-500">Override authority: {p.override_capability?.replaceAll('_',' ')??'Not overridable'}</p></article>)}{!isLoading&&!active.length&&!isError&&<div className="rounded-2xl border border-dashed border-white/[.08] p-8 text-center text-xs text-zinc-600">No studio standards configured yet.</div>}</div></section>
      <section><div className="flex items-center gap-2"><AlertTriangle size={15} className="text-amber-300"/><h2 className="text-xs font-semibold uppercase tracking-wider">Exception queue</h2></div><div className="mt-4 space-y-3">{waiting.map(item=><article key={item.id} className="rounded-2xl border border-amber-300/10 bg-amber-300/[.02] p-5"><p className="text-[8px] uppercase text-amber-300">Outside {item.policy.name}</p><h3 className="mt-2 text-sm">{item.target_type.replaceAll('_',' ')} · {item.target_id}</h3><p className="mt-3 text-xs leading-5 text-zinc-500">{item.reason}</p>{item.consequence?.summary&&<p className="mt-3 rounded-xl bg-black/20 p-3 text-[10px] text-zinc-500">Consequence: {item.consequence.summary}</p>}<div className="mt-4 flex gap-2"><button type="button" disabled={decide.isPending} onClick={()=>decide.mutate({id:item.id,decision:'APPROVE'})} className="inline-flex items-center gap-1 rounded-lg bg-emerald-400 px-3 py-2 text-[8px] font-semibold text-black"><Check size={11}/>Approve</button><button type="button" disabled={decide.isPending} onClick={()=>decide.mutate({id:item.id,decision:'REJECT'})} className="rounded-lg border border-red-400/15 px-3 py-2 text-[8px] text-red-300">Reject</button><button type="button" disabled={decide.isPending} onClick={()=>decide.mutate({id:item.id,decision:'ESCALATE'})} className="rounded-lg border border-white/[.08] px-3 py-2 text-[8px] text-zinc-500">Escalate</button></div></article>)}{!waiting.length&&<div className="rounded-2xl border border-dashed border-white/[.08] p-8 text-center text-xs text-zinc-600">No exceptions need a decision.</div>}</div></section></div>
  </div></main>
}
